### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by mborejdo** [vihu/gogo#6]
Hey there, first of all, thanks for gogo. Nice handy tool in the rust universe.

I am not sure, what is happening here:
I install gogo from cargo like this: `cargo install --version 1.0.1 gogo --force` to make sure I have the export command.

The installed binary does not have the export subcommand, though.

```
gogo --version
gogo 1.0
```

I am pretty sure i am calling the recently installed 1.0.1 though

**Comment by vihu** [comment]
That's odd, I just tried this locally:

```bash
╭─rahul@rg-mbp ~
╰─$ cargo install --version 1.0.1 gogo                                                                                                   130 ↵
     Ignored package `gogo v1.0.1` is already installed, use --force to override
╭─rahul@rg-mbp ~
╰─$ GOGODB_PATH=/tmp/gogo.db gogo --help
gogo 1.0
A mnemonic url opener

USAGE:
    gogo [mnemonic] [SUBCOMMAND]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

ARGS:
    <mnemonic>    The mnemonic to open

SUBCOMMANDS:
    add            Add url mnemonic mapping
    export         Export to CSV
    get_browser    Get currently configured browser
    help           Prints this message or the help of the given subcommand(s)
    list           List mnemonic url mapping
    open           Open url using mnemonic
    rm             Remove mnemonic
    search         Construct /search?q= query for known mnemonic
    set_browser    Allow setting preferred browser
╭─rahul@rg-mbp ~
╰─$ GOGODB_PATH=/tmp/gogo.db gogo export
output written to "/tmp/gogo_1666165586807.csv"
```

I would suggest just trying a `cargo uninstall gogo`, then `cargo install --version 1.0.1 gogo`, making sure you have the right DB path exported (shouldn't have to change it if you've put it in you bashrc/zshrc). And then retry the `export` subcommand. Note that you don't have to specify any extra args to it, its just `gogo export`.

PS: Just as an extra precaution, please ensure that you at least keep a copy of your export DB somewhere. It's a chore to redo the mnemonics if you have slowly built a giant one (like I have)

PPS: I do notice that I've mungled the actual version the `gogo` executable outputs though (i.e. it will always report `1.0`, I intend to fix that tomorrow, but I don't really want to overwrite tags, so from version `2.0.*` onwards, it should all line up.

**Comment by mborejdo** [comment]
thanks for looking into this! I managed to export the list manually to csv, as its pretty short at the moment,  and re-import it with 2.0.0 But larger lists would defenitely be easier to handle with a working import/export flow.

**Comment by vihu** [comment]
> thanks for looking into this! I managed to export the list manually to csv, as its pretty short at the moment, and re-import it with 2.0.0 But larger lists would defenitely be easier to handle with a working import/export flow.

Nice, yeah, sorry about that. Things should be smoother `v2.0.*` onwards 🤞
